[profile.foundry]
src = ["contracts", "test", "helpers"]
out = "out"
libs = ["lib"]
remappings = [
    "aave-v3-core/=lib/aave-v3-core/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.solc]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"
evm_version = "paris"

[profile.test]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 15 }
